-- Create missing admin feature tables and RLS policies

-- Create tables if they don't exist (from admin features migration)
CREATE TABLE IF NOT EXISTS public.subscription_plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  price numeric NOT NULL DEFAULT 0,
  duration_months integer NOT NULL DEFAULT 1,
  features text[] DEFAULT '{}',
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
  plan_id bigint NOT NULL REFERENCES public.subscription_plans(id) ON DELETE CASCADE,
  start_date timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  end_date timestamp with time zone NOT NULL,
  status text DEFAULT 'active' CHECK (status IN ('active', 'expired', 'cancelled')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.commission_rates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role public.user_role NOT NULL,
  rate numeric NOT NULL DEFAULT 0,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id bigint NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
  amount numeric NOT NULL,
  commission_amount numeric NOT NULL DEFAULT 0,
  commission_status text DEFAULT 'pending' CHECK (commission_status IN ('pending', 'paid', 'refunded')),
  payment_status text DEFAULT 'pending' CHECK (payment_status IN ('pending', 'completed', 'failed', 'refunded')),
  payment_method text,
  description text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.flags (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_type text NOT NULL CHECK (item_type IN ('property', 'user', 'inquiry', 'application')),
  item_id bigint NOT NULL,  -- Changed to bigint to match property id
  reporter_id uuid NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
  reason text NOT NULL,
  description text,
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'resolved')),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  resolved_at timestamp with time zone,
  resolved_by uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.support_tickets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
  subject text NOT NULL,
  message text NOT NULL,
  status text DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'closed')),
  priority text DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high')),
  assigned_to uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.support_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id bigint NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE,
  sender_id uuid NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.property_verifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id bigint NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
  verified_by uuid NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'verified', 'rejected')),
  notes text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create indexes if they don't exist
CREATE INDEX IF NOT EXISTS idx_flags_reporter_id ON public.flags(reporter_id);
CREATE INDEX IF NOT EXISTS idx_flags_item_type_item_id ON public.flags(item_type, item_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_user_id ON public.support_tickets(user_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON public.support_tickets(status);
CREATE INDEX IF NOT EXISTS idx_support_messages_ticket_id ON public.support_messages(ticket_id);
CREATE INDEX IF NOT EXISTS idx_support_messages_sender_id ON public.support_messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_transactions_property_id ON public.transactions(property_id);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON public.transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_property_verifications_property_id ON public.property_verifications(property_id);
CREATE INDEX IF NOT EXISTS idx_property_verifications_verified_by ON public.property_verifications(verified_by);

-- Enable RLS for all tables and create clean policies
ALTER TABLE public.subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.commission_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.flags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.property_verifications ENABLE ROW LEVEL SECURITY;

-- Subscription Plans RLS
DROP POLICY IF EXISTS "Admins can access all subscription plans" ON public.subscription_plans;
CREATE POLICY "Admins can access all subscription plans" ON public.subscription_plans 
FOR ALL TO authenticated USING ((SELECT role FROM public.user_profiles WHERE id = auth.uid()) = 'admin');

-- User Subscriptions RLS
DROP POLICY IF EXISTS "Users can access their own subscriptions" ON public.user_subscriptions;
DROP POLICY IF EXISTS "Admins can access all user subscriptions" ON public.user_subscriptions;
CREATE POLICY "Users can access their own subscriptions" ON public.user_subscriptions
FOR ALL TO authenticated USING (user_id = auth.uid());
CREATE POLICY "Admins can access all user subscriptions" ON public.user_subscriptions
FOR ALL TO authenticated USING ((SELECT role FROM public.user_profiles WHERE id = auth.uid()) = 'admin');

-- Commission Rates RLS
DROP POLICY IF EXISTS "Authenticated users can view active commission rates" ON public.commission_rates;
DROP POLICY IF EXISTS "Admins can manage all commission rates" ON public.commission_rates;
CREATE POLICY "Authenticated users can view active commission rates" ON public.commission_rates
FOR SELECT TO authenticated USING (is_active = true AND auth.role() = 'authenticated');
CREATE POLICY "Admins can manage all commission rates" ON public.commission_rates
FOR ALL TO authenticated USING ((SELECT role FROM public.user_profiles WHERE id = auth.uid()) = 'admin');

-- Transactions RLS
DROP POLICY IF EXISTS "Users can access their own transactions" ON public.transactions;
DROP POLICY IF EXISTS "Admins can access all transactions" ON public.transactions;
DROP POLICY IF EXISTS "Agents can access transactions for their properties" ON public.transactions;
CREATE POLICY "Users can access their own transactions" ON public.transactions
FOR ALL TO authenticated USING (user_id = auth.uid());
CREATE POLICY "Admins can access all transactions" ON public.transactions
FOR ALL TO authenticated USING ((SELECT role FROM public.user_profiles WHERE id = auth.uid()) = 'admin');
CREATE POLICY "Agents can access transactions for their properties" ON public.transactions
FOR SELECT TO authenticated USING (EXISTS (
    SELECT 1 FROM public.properties
    WHERE properties.id = transactions.property_id AND properties.agent_id = auth.uid()
));

-- Flags RLS
DROP POLICY IF EXISTS "Users can create flags" ON public.flags;
DROP POLICY IF EXISTS "Users can view and update their own flags" ON public.flags;
DROP POLICY IF EXISTS "Admins can manage all flags" ON public.flags;
CREATE POLICY "Users can create flags" ON public.flags
FOR INSERT TO authenticated WITH CHECK (reporter_id = auth.uid());
CREATE POLICY "Users can view and update their own flags" ON public.flags
FOR ALL TO authenticated USING (reporter_id = auth.uid());
CREATE POLICY "Admins can manage all flags" ON public.flags
FOR ALL TO authenticated USING ((SELECT role FROM public.user_profiles WHERE id = auth.uid()) = 'admin');

-- Support Tickets RLS
DROP POLICY IF EXISTS "Users can create and manage their own tickets" ON public.support_tickets;
DROP POLICY IF EXISTS "Admins can access all support tickets" ON public.support_tickets;
DROP POLICY IF EXISTS "Admins can manage assigned support tickets" ON public.support_tickets;
CREATE POLICY "Users can create and manage their own tickets" ON public.support_tickets
FOR ALL TO authenticated USING (user_id = auth.uid());
CREATE POLICY "Admins can access all support tickets" ON public.support_tickets
FOR ALL TO authenticated USING ((SELECT role FROM public.user_profiles WHERE id = auth.uid()) = 'admin');
CREATE POLICY "Admins can manage assigned support tickets" ON public.support_tickets
FOR ALL TO authenticated USING (assigned_to = auth.uid());

-- Support Messages RLS
DROP POLICY IF EXISTS "Users can create messages for their tickets" ON public.support_messages;
DROP POLICY IF EXISTS "Users and admins can view messages for their tickets" ON public.support_messages;
DROP POLICY IF EXISTS "Admins can manage all support messages" ON public.support_messages;
CREATE POLICY "Users can create messages for their tickets" ON public.support_messages
FOR INSERT TO authenticated WITH CHECK (EXISTS (
  SELECT 1 FROM public.support_tickets
  WHERE support_tickets.id = ticket_id AND support_tickets.user_id = auth.uid()
));
CREATE POLICY "Users and admins can view messages for their tickets" ON public.support_messages
FOR SELECT TO authenticated USING (
  EXISTS (
    SELECT 1 FROM public.support_tickets
    WHERE support_tickets.id = support_messages.ticket_id AND support_tickets.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM public.support_tickets
    WHERE support_tickets.id = support_messages.ticket_id AND support_tickets.assigned_to = auth.uid()
  )
  OR (SELECT role FROM public.user_profiles WHERE id = auth.uid()) = 'admin'
);
CREATE POLICY "Admins can manage all support messages" ON public.support_messages
FOR ALL TO authenticated USING ((SELECT role FROM public.user_profiles WHERE id = auth.uid()) = 'admin');

-- Property Verifications RLS
DROP POLICY IF EXISTS "Property owners can view verifications for their properties" ON public.property_verifications;
DROP POLICY IF EXISTS "Admins can manage all property verifications" ON public.property_verifications;
CREATE POLICY "Property owners can view verifications for their properties" ON public.property_verifications
FOR SELECT TO authenticated USING (EXISTS (
  SELECT 1 FROM public.properties
  WHERE properties.id = property_verifications.property_id AND properties.landlord_id = auth.uid()
));
CREATE POLICY "Admins can manage all property verifications" ON public.property_verifications
FOR ALL TO authenticated USING ((SELECT role FROM public.user_profiles WHERE id = auth.uid()) = 'admin');

-- Insert default data if needed
INSERT INTO public.commission_rates (role, rate, description, is_active) 
SELECT 'landlord', 5.0, 'Commission for landlord property listings', true
WHERE NOT EXISTS (SELECT 1 FROM commission_rates WHERE role = 'landlord');

INSERT INTO public.commission_rates (role, rate, description, is_active) 
SELECT 'agent', 3.5, 'Commission for agent-facilitated transactions', true
WHERE NOT EXISTS (SELECT 1 FROM commission_rates WHERE role = 'agent');

INSERT INTO public.commission_rates (role, rate, description, is_active) 
SELECT 'student', 1.0, 'Fee for premium student features', true
WHERE NOT EXISTS (SELECT 1 FROM commission_rates WHERE role = 'student');

INSERT INTO public.subscription_plans (name, price, duration_months, features, is_active) 
SELECT 'Basic Plan', 0.00, 1, ARRAY['Basic property listings', 'Email support'], true
WHERE NOT EXISTS (SELECT 1 FROM subscription_plans WHERE name = 'Basic Plan');

INSERT INTO public.subscription_plans (name, price, duration_months, features, is_active) 
SELECT 'Premium Plan', 9.99, 1, ARRAY['Unlimited listings', 'Priority support', 'Featured listings'], true
WHERE NOT EXISTS (SELECT 1 FROM subscription_plans WHERE name = 'Premium Plan');

INSERT INTO public.subscription_plans (name, price, duration_months, features, is_active) 
SELECT 'Professional Plan', 29.99, 1, ARRAY['All Premium features', 'Analytics dashboard', 'Custom branding'], true
WHERE NOT EXISTS (SELECT 1 FROM subscription_plans WHERE name = 'Professional Plan');